/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ContattiRouteImport } from './routes/contatti'
import { Route as CookiePolicyRouteImport } from './routes/cookie-policy'
import { Route as GraziePreventivoRouteImport } from './routes/grazie-preventivo'
import { Route as MayaAppRouteImport } from './routes/maya-app'
import { Route as MayaConnectRouteImport } from './routes/maya-connect'
import { Route as MayaWebRouteImport } from './routes/maya-web'
import { Route as NoteLegaliRouteImport } from './routes/note-legali'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as PreventivoRouteImport } from './routes/preventivo'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as ApiPreventivoRouteImport } from './routes/api.preventivo'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContattiRoute = ContattiRouteImport.update({
  id: '/contatti',
  path: '/contatti',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiePolicyRoute = CookiePolicyRouteImport.update({
  id: '/cookie-policy',
  path: '/cookie-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const GraziePreventivoRoute = GraziePreventivoRouteImport.update({
  id: '/grazie-preventivo',
  path: '/grazie-preventivo',
  getParentRoute: () => rootRouteImport,
} as any)
const MayaAppRoute = MayaAppRouteImport.update({
  id: '/maya-app',
  path: '/maya-app',
  getParentRoute: () => rootRouteImport,
} as any)
const MayaConnectRoute = MayaConnectRouteImport.update({
  id: '/maya-connect',
  path: '/maya-connect',
  getParentRoute: () => rootRouteImport,
} as any)
const MayaWebRoute = MayaWebRouteImport.update({
  id: '/maya-web',
  path: '/maya-web',
  getParentRoute: () => rootRouteImport,
} as any)
const NoteLegaliRoute = NoteLegaliRouteImport.update({
  id: '/note-legali',
  path: '/note-legali',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const PreventivoRoute = PreventivoRouteImport.update({
  id: '/preventivo',
  path: '/preventivo',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPreventivoRoute = ApiPreventivoRouteImport.update({
  id: '/api/preventivo',
  path: '/api/preventivo',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contatti': typeof ContattiRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/grazie-preventivo': typeof GraziePreventivoRoute
  '/maya-app': typeof MayaAppRoute
  '/maya-connect': typeof MayaConnectRoute
  '/maya-web': typeof MayaWebRoute
  '/note-legali': typeof NoteLegaliRoute
  '/portfolio': typeof PortfolioRoute
  '/preventivo': typeof PreventivoRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/api/preventivo': typeof ApiPreventivoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contatti': typeof ContattiRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/grazie-preventivo': typeof GraziePreventivoRoute
  '/maya-app': typeof MayaAppRoute
  '/maya-connect': typeof MayaConnectRoute
  '/maya-web': typeof MayaWebRoute
  '/note-legali': typeof NoteLegaliRoute
  '/portfolio': typeof PortfolioRoute
  '/preventivo': typeof PreventivoRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/api/preventivo': typeof ApiPreventivoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contatti': typeof ContattiRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/grazie-preventivo': typeof GraziePreventivoRoute
  '/maya-app': typeof MayaAppRoute
  '/maya-connect': typeof MayaConnectRoute
  '/maya-web': typeof MayaWebRoute
  '/note-legali': typeof NoteLegaliRoute
  '/portfolio': typeof PortfolioRoute
  '/preventivo': typeof PreventivoRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/api/preventivo': typeof ApiPreventivoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contatti'
    | '/cookie-policy'
    | '/grazie-preventivo'
    | '/maya-app'
    | '/maya-connect'
    | '/maya-web'
    | '/note-legali'
    | '/portfolio'
    | '/preventivo'
    | '/privacy-policy'
    | '/api/preventivo'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contatti'
    | '/cookie-policy'
    | '/grazie-preventivo'
    | '/maya-app'
    | '/maya-connect'
    | '/maya-web'
    | '/note-legali'
    | '/portfolio'
    | '/preventivo'
    | '/privacy-policy'
    | '/api/preventivo'
  id:
    | '__root__'
    | '/'
    | '/contatti'
    | '/cookie-policy'
    | '/grazie-preventivo'
    | '/maya-app'
    | '/maya-connect'
    | '/maya-web'
    | '/note-legali'
    | '/portfolio'
    | '/preventivo'
    | '/privacy-policy'
    | '/api/preventivo'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContattiRoute: typeof ContattiRoute
  CookiePolicyRoute: typeof CookiePolicyRoute
  GraziePreventivoRoute: typeof GraziePreventivoRoute
  MayaAppRoute: typeof MayaAppRoute
  MayaConnectRoute: typeof MayaConnectRoute
  MayaWebRoute: typeof MayaWebRoute
  NoteLegaliRoute: typeof NoteLegaliRoute
  PortfolioRoute: typeof PortfolioRoute
  PreventivoRoute: typeof PreventivoRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  ApiPreventivoRoute: typeof ApiPreventivoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contatti': {
      id: '/contatti'
      path: '/contatti'
      fullPath: '/contatti'
      preLoaderRoute: typeof ContattiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookie-policy': {
      id: '/cookie-policy'
      path: '/cookie-policy'
      fullPath: '/cookie-policy'
      preLoaderRoute: typeof CookiePolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grazie-preventivo': {
      id: '/grazie-preventivo'
      path: '/grazie-preventivo'
      fullPath: '/grazie-preventivo'
      preLoaderRoute: typeof GraziePreventivoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maya-app': {
      id: '/maya-app'
      path: '/maya-app'
      fullPath: '/maya-app'
      preLoaderRoute: typeof MayaAppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maya-connect': {
      id: '/maya-connect'
      path: '/maya-connect'
      fullPath: '/maya-connect'
      preLoaderRoute: typeof MayaConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maya-web': {
      id: '/maya-web'
      path: '/maya-web'
      fullPath: '/maya-web'
      preLoaderRoute: typeof MayaWebRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/note-legali': {
      id: '/note-legali'
      path: '/note-legali'
      fullPath: '/note-legali'
      preLoaderRoute: typeof NoteLegaliRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preventivo': {
      id: '/preventivo'
      path: '/preventivo'
      fullPath: '/preventivo'
      preLoaderRoute: typeof PreventivoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/preventivo': {
      id: '/api/preventivo'
      path: '/api/preventivo'
      fullPath: '/api/preventivo'
      preLoaderRoute: typeof ApiPreventivoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContattiRoute: ContattiRoute,
  CookiePolicyRoute: CookiePolicyRoute,
  GraziePreventivoRoute: GraziePreventivoRoute,
  MayaAppRoute: MayaAppRoute,
  MayaConnectRoute: MayaConnectRoute,
  MayaWebRoute: MayaWebRoute,
  NoteLegaliRoute: NoteLegaliRoute,
  PortfolioRoute: PortfolioRoute,
  PreventivoRoute: PreventivoRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  ApiPreventivoRoute: ApiPreventivoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
