/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MayaAppRouteImport } from './routes/maya-app'
import { Route as MayaConnectRouteImport } from './routes/maya-connect'
import { Route as MayaWebRouteImport } from './routes/maya-web'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MayaAppRoute = MayaAppRouteImport.update({
  id: '/maya-app',
  path: '/maya-app',
  getParentRoute: () => rootRouteImport,
} as any)
const MayaConnectRoute = MayaConnectRouteImport.update({
  id: '/maya-connect',
  path: '/maya-connect',
  getParentRoute: () => rootRouteImport,
} as any)
const MayaWebRoute = MayaWebRouteImport.update({
  id: '/maya-web',
  path: '/maya-web',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/maya-app': typeof MayaAppRoute
  '/maya-connect': typeof MayaConnectRoute
  '/maya-web': typeof MayaWebRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/maya-app': typeof MayaAppRoute
  '/maya-connect': typeof MayaConnectRoute
  '/maya-web': typeof MayaWebRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/maya-app': typeof MayaAppRoute
  '/maya-connect': typeof MayaConnectRoute
  '/maya-web': typeof MayaWebRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/maya-app' | '/maya-connect' | '/maya-web'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/maya-app' | '/maya-connect' | '/maya-web'
  id: '__root__' | '/' | '/maya-app' | '/maya-connect' | '/maya-web'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MayaAppRoute: typeof MayaAppRoute
  MayaConnectRoute: typeof MayaConnectRoute
  MayaWebRoute: typeof MayaWebRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maya-app': {
      id: '/maya-app'
      path: '/maya-app'
      fullPath: '/maya-app'
      preLoaderRoute: typeof MayaAppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maya-connect': {
      id: '/maya-connect'
      path: '/maya-connect'
      fullPath: '/maya-connect'
      preLoaderRoute: typeof MayaConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maya-web': {
      id: '/maya-web'
      path: '/maya-web'
      fullPath: '/maya-web'
      preLoaderRoute: typeof MayaWebRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MayaAppRoute: MayaAppRoute,
  MayaConnectRoute: MayaConnectRoute,
  MayaWebRoute: MayaWebRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
